"use client";
import NextAuthProvider from "./Providers";
import "./globals.css";
import { Inter } from "next/font/google";
import { WagmiConfig, createConfig } from "wagmi";
import {
  ConnectKitProvider,
  ConnectKitButton,
  getDefaultConfig,
} from "connectkit";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Liveloud",
  description: "Generated by create next app",
};

const config = createConfig(
  getDefaultConfig({
    // Required API Keys
    alchemyId: process.env.ALCHEMY_ID, // or infuraId
    walletConnectProjectId: process.env.WEB3_PROJECT_ID,

    // Required
    appName: "LiveLoud",

    // Optional
    appDescription: "Your App Description",
    appUrl: "https://family.co", // your app's url
    appIcon: "https://family.co/logo.png", // your app's icon, no bigger than 1024x1024px (max. 1MB)
  })
);

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NextAuthProvider>
          <WagmiConfig config={config}>
            <ConnectKitProvider>
              {/* <ConnectKitButton /> */}
              {children}
            </ConnectKitProvider>
          </WagmiConfig>
        </NextAuthProvider>
      </body>
    </html>
  );
}
