"use client";
import NextAuthProvider from "./Providers";
import "./globals.css";
import { Inter } from "next/font/google";
import {
  EthereumClient,
  w3mConnectors,
  w3mProvider,
} from "@web3modal/ethereum";
import { Web3Modal } from "@web3modal/react";
import { configureChains, createConfig, WagmiConfig } from "wagmi";
import { arbitrum, mainnet, polygon } from "wagmi/chains";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Liveloud",
  description: "Generated by create next app",
};

const chains = [arbitrum, mainnet, polygon];
const projectId = "7f6f2dadd3a11c04f6a651f28265e8d3";

const { publicClient } = configureChains(chains, [w3mProvider({ projectId })]);
const wagmiConfig = createConfig({
  autoConnect: true,
  connectors: w3mConnectors({ projectId, chains }),
  publicClient,
});
const ethereumClient = new EthereumClient(wagmiConfig, chains);

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NextAuthProvider>
          <WagmiConfig config={wagmiConfig}>
            {children}
            <Web3Modal projectId={projectId} ethereumClient={ethereumClient} />
          </WagmiConfig>
        </NextAuthProvider>
      </body>
    </html>
  );
}
